version: 0.2

phases:
  install:
    commands:
      - pip install -r requirements.txt -t .
  build:
    commands:
      - zip -r lambda_function.zip .
  post_build:
    commands:
      - echo "Tests passed"

artifacts:
  files:
    - lambda_function.zip
