version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing Python 3.9"
      - python --version
      
  pre_build:
    commands:
      - echo "=========================================="
      - echo "PRE_BUILD - Verifying Files"
      - echo "=========================================="
      - pwd
      - ls -lah
      - echo "Checking lambda_function.py..."
      - ls -l lambda_function.py
      
  build:
    commands:
      - echo "=========================================="
      - echo "BUILD - Creating Deployment Package"
      - echo "=========================================="
      - zip lambda-deployment-package.zip lambda_function.py
      - ls -lh lambda-deployment-package.zip
      - unzip -l lambda-deployment-package.zip
      - echo "Build completed!"
      
  post_build:
    commands:
      - echo "Artifact ready"

artifacts:
  files:
    - lambda-deployment-package.zip
  name: BuildArtifact
