version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
      
  build:
    commands:
      - echo "Build started"
      - ls -la
      - zip lambda-deployment-package.zip lambda_function.py
      - ls -la lambda-deployment-package.zip
      
artifacts:
  files:
    - lambda-deployment-package.zip
